# With this workflow, whenever you publish a new release, 
# GitHub will trigger the workflow and run the deploy job, 
# which will install the dependencies, build the project, 
# and deploy the new or updated files to the remote server.

name: Release Deploy Workflow

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  #    - name: Cache dependencies
  #      uses: actions/cache@v2
  #      with:
  #        path: ~/.composer/cache/files
  #        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "composer_dir={$(composer config cache-files-dir)}" >> $GITHUB_OUTPUT

      - name: Retrieve Composer‘s cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.composer_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install all other dependencies
        run: composer require -W figuren-theater/ft-platform-curation:dev-main
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          timeout: 180000 # 3 min
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/wp-content/**
            **/.editorconfig
            
